In [41]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np

In [5]:
df = pd.read_csv('/content/drive/MyDrive/DataScience/RecommSys/popmovies.CSV', index_col=0)
print(df.shape)
df.head()

(10000, 5)


title  ... vote_average
0                        Ad Astra  ...          5.9
1                       Bloodshot  ...          7.2
2               Bad Boys for Life  ...          7.1
3                         Ant-Man  ...          7.1
4  Percy Jackson: Sea of Monsters  ...          5.9

[5 rows x 5 columns]

In [10]:
df.isnull().sum()

title                 0
overview             30
original_language     0
vote_count            0
vote_average          0
dtype: int64

In [11]:
df.dropna(inplace=True)

In [38]:
# Vectorizing the data
tfidf = TfidfVectorizer(min_df=4, max_df=0.7)

vectorized_data = tfidf.fit_transform(df['overview'])
print(vectorized_data.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [39]:
tfidf_df = pd.DataFrame(vectorized_data.toarray(), 
                        columns=tfidf.get_feature_names())
tfidf_df.index = df['title']
tfidf_df

000  007   10  100  ...  zone  zones  zoo  zooey
title                                               ...                         
Ad Astra                        0.0  0.0  0.0  0.0  ...   0.0    0.0  0.0    0.0
Bloodshot                       0.0  0.0  0.0  0.0  ...   0.0    0.0  0.0    0.0
Bad Boys for Life               0.0  0.0  0.0  0.0  ...   0.0    0.0  0.0    0.0
Ant-Man                         0.0  0.0  0.0  0.0  ...   0.0    0.0  0.0    0.0
Percy Jackson: Sea of Monsters  0.0  0.0  0.0  0.0  ...   0.0    0.0  0.0    0.0
...                             ...  ...  ...  ...  ...   ...    ...  ...    ...
Cargo                           0.0  0.0  0.0  0.0  ...   0.0    0.0  0.0    0.0
The Good Night                  0.0  0.0  0.0  0.0  ...   0.0    0.0  0.0    0.0
The World Is Yours              0.0  0.0  0.0  0.0  ...   0.0    0.0  0.0    0.0
The Grand Seduction             0.0  0.0  0.0  0.0  ...   0.0    0.0  0.0    0.0
Woochi: The Demon Slayer        0.0  0.0  0.0  0.0  ...   0.0    0.0  0.0    0.0

[9970 rows x 9379 columns]

In [40]:
from sklearn.metrics.pairwise import cosine_similarity

cosine_similarity_array = cosine_similarity(tfidf_df)

In [42]:
cosine_sim_df = pd.DataFrame(cosine_similarity_array, index = tfidf_df.index, columns = tfidf_df.index)
print(cosine_sim_df)

title                           Ad Astra  ...  Woochi: The Demon Slayer
title                                     ...                          
Ad Astra                        1.000000  ...                  0.006578
Bloodshot                       0.032822  ...                  0.033893
Bad Boys for Life               0.006165  ...                  0.004751
Ant-Man                         0.008447  ...                  0.043655
Percy Jackson: Sea of Monsters  0.006024  ...                  0.006482
...                                  ...  ...                       ...
Cargo                           0.068984  ...                  0.024750
The Good Night                  0.020412  ...                  0.011627
The World Is Yours              0.018521  ...                  0.003046
The Grand Seduction             0.014346  ...                  0.004441
Woochi: The Demon Slayer        0.006578  ...                  1.000000

[9970 rows x 9970 columns]


In [47]:
cosine_sim_df.loc['Bad Boys for Life'].sort_values(ascending=False).head()

title
Bad Boys for Life    1.000000
Bad Boys II          0.329347
Scarface             0.197642
Ride Along 2         0.183544
Bad Boys             0.175233
Name: Bad Boys for Life, dtype: float64

In [46]:
print(f"Supposed the user watched 'Bad Boys for Life', the most similar movies based on movie's overview are: {cosine_sim_df.loc['Bad Boys for Life'].sort_values(ascending=False).head()[1:].index}")

Supposed the user watched 'Bad Boys for Life', the most similar movies based on movie's overview are: Index(['Bad Boys II', 'Scarface', 'Ride Along 2', 'Bad Boys'], dtype='object', name='title')
